
platform :ios, '7.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/anodamobi/ANODA-CocoaPods.git'
source 'https://github.com/noplanb/Private-Cocoapods.git'

#ignore all warnings from all pods
inhibit_all_warnings!


target 'Zazo' do
    
    #ANODA
    pod 'ANBaseDomainModel', '~> 1.0'
    pod 'ANHelperFunctions', '~> 1.0.3'
    pod 'ANCategories', '~> 1.0.6'
    pod 'ANStorage', '~> 1.1.3'
    pod 'ANTableController', '~> 1.1.5'
    pod 'ANTableViews', '~> 1.0.10'
#    :path => '~/Development/ANODA/ANTableViews/'
#
    pod 'ANLogger', '~> 1.0.2'
    pod 'ANColorTheme', '~> 1.0.4'
    pod 'ANProgressButton', '~> 1.0.2'
    pod 'ANKeyboardHandler', '~> 1.0.2'
    pod 'ANCollectonController', '~> 1.0'
    
    #UI
    pod 'FrameAccessor', '~> 1.3.2'
    pod 'HexColors', '~> 2.3.0'
    pod 'APAddressBook', '~> 0.1.11'
    pod 'libPhoneNumber-iOS', '~> 0.8.7'
    pod 'SVProgressHUD', '~> 1.1.3'
    
    #UI
    pod 'Masonry', '~> 0.6.2'
    pod 'MSSPopMasonry', '~> 0.0.1'
    pod 'SDWebImage', '~> 3.7.3'
    pod 'POP+MCAnimate', '~> 2.0'
    
    #Testing
    pod 'Reveal-iOS-SDK', '~> 1.5.1', :configurations => ['Debug']
    pod 'Fabric', '~> 1.5'
    pod 'Crashlytics', '~> 3.3.4'
    
    pod 'KVOController', '~> 1.0.3'
    
    #Core Data
    pod 'FastEasyMapping', '~> 0.5.1'
    pod 'MagicalRecord', '~> 2.3.0'
    
    #Helpers
    pod 'DeviceUtil', '~> 1.2.0'
    
    #! ----- debugging tools, remove on prod --------- !
    pod 'CocoaLumberjack', '~> 2.0.1'
    pod 'Rollbar', '~> 0.1.5'
    
    pod 'AFNetworking', '~> 2.6.0'
    pod 'OBLogger', '~> 0.2.1'
    pod 'OBFileTransfer', '~> 0.5.7'
    pod 'UIAlertView+Blocks', '~> 0.9'
    pod 'SDCAlertView', '~> 2.5.2'
    pod 'SDCAutoLayout', '~> 2.0.3'
    pod 'iToast', '~> 0.0.1'
    pod 'SCRecorder'

end


target 'ZazoTests' do
    
    pod 'ANHelperFunctions', '~> 1.0.3'
    pod 'Specta', '~> 1.0.3'
    pod 'Expecta', '~> 1.0.2'
    pod 'KIF', '~> 3.2.3'
    
end

