
platform :ios, '8.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/noplanb/Private-Cocoapods.git'

inhibit_all_warnings!
use_frameworks!

target 'Zazo' do

    link_with 'Zazo', 'Zazo-NetworkTest'

    #UI
    pod 'FrameAccessor', '~> 1.3.2'
    pod 'SVProgressHUD', '~> 1.1.3'
    pod 'pop', '~> 1.0'
    pod 'Masonry', '~> 0.6.2'
    pod 'TPKeyboardAvoiding'
    pod 'OAStackView', '~> 1.0'
    pod 'UIAlertView+Blocks', '~> 0.9'
    pod 'SDCAlertView', '~> 2.5.2'
    pod 'SDCAutoLayout', '~> 2.0.3'
    pod 'PermissionScope'
    
    #Network
    pod 'OBFileTransfer', '0.9.2'
    pod 'AFNetworking', '~> 2.6.0'

    #Testing
    pod 'Reveal-iOS-SDK', '~> 1.6.1', :configurations => ['Debug']
    pod 'Fabric', '~> 1.6.1'
    pod 'Crashlytics', '~> 3.7.0'

    #Core Data
    pod 'FastEasyMapping', '~> 0.5.1'
    pod 'MagicalRecord', '~> 2.3.0'

    #Video
    pod 'PBJVision', git: 'https://github.com/noplanb/PBJVision', tag: 'v0.4.6'
    pod 'iToast', '~> 0.0.1'

    #Misc
    pod 'DeviceUtil', '~> 1.2.0'
    pod 'ReactiveCocoa', '~> 2.4.7'
    pod 'APAddressBook', '~> 0.2.1'
    pod 'libPhoneNumber-iOS', '~> 0.8.7'

    #Logging
    pod 'Rollbar', '~> 0.1.5'
    pod 'OBLogger', '~> 0.3.0'
end


target 'ZazoTests' do
    pod 'Specta', '~> 1.0.3'
    pod 'Expecta', '~> 1.0.2'
    pod 'KIF', '~> 3.2.3'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
end
